config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    get 'customers/edit' => 'customers#edit'
    get 'customers' => 'customers#show'
  end
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'public/homes#top'
   namespace :admin do
       resources :customers, only: [:index, :show, :edit, :update]
       get 'admin' => 'homes#top'
       resources :items, except: [:destroy]
       resources :genres, only: [:index, :create, :edit, :update]
       resources :orders, only: [:show,:update]
       resources :order_details, only: [:update]
   end
   scope module: :public do
     delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
     resources :cart_items, only: [:index, :create, :update, :destroy]
     get 'about' => 'homes#about'
     resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :show, :update]
     get 'customers/withdraw' => 'customers#withdraw'
     patch 'customers/withdraw_update' => 'customers#withdsraw_update'
     get 'orders/thanks' => 'orders#thanks'
     post 'orders/verification' => 'orders#verification'
     resources :orders, only: [:new, :show, :index, :create]
     resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def view_dear_address
    self.postal_code + self.address + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cart_items
         has_many :addresses
         has_many :orders

         def fullname
          last_name+first_name
         end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    validates :image, presence: true
    validates :name, presence: true
    validates :introduction, presence: true
    validates :genre_id, presence: true
    validates :price, presence: true
    validates :is_active, presence: true

    belongs_to :genre
    has_many :cart_items
    has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4
  }

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3
  }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end
private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    end
  end

 private
    def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :price, :is_active)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id)
    end
  end

  private
   def order_params
      params.require(:order).permit(:status)
   end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_admin_path
    else
      root_path
    end
 end


  protected


  def configure_permitted_parameters
    if resource_name==:customer
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h4>ジャンル編集</h4>
 <%= form_with model: @genre, url:admin_genre_path, local: true do |f|%>
<table>
  <tbody>

    <tr>
      <td><strong><%=f.label :ジャンル名 %></strong><td>
      <td><%= f.text_field :name, autofocus: true %></td>
      <td><%= f.submit "変更を保存",class: "btn btn-success" %></td>

    </tr>
  </tbody>
</table>
 <% end %>

app/views/admin/genres/index.html.erb
<h4>ジャンル一覧·追加</h4>
<div class="container">
  <div class="row">
    <div class="col-lg-4">
       <%= form_with model: @genre, url:admin_genres_path, local: true do |f|%>
    <table>
    <tbody>
      <tr>
        <td><%= f.label :ジャンル名 %><td>
        <td><%= f.text_field :name, :placeholder => "ジャンル名" ,autofocus: true %></td>
        <td><%= f.submit "新規登録",class: "btn btn-success" %></td>
      </tr>

  </tbody>
</table>
 <% end %>

<table class="table">
  <thead class="thead-dark"><strong>ジャンル</strong></thead>
  <tbody>
    <% @genres.each do |genre|%>
      <tr>
        <td>
         <%= genre.name%>
        </td>
        <td><%= link_to "編集する", edit_admin_genre_path(genre) ,class: "btn btn-success"%> </td>
      </tr>
    <% end %>
  </tbody>
  </table>
  </div>

  </div>
</div>

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>

<div class="container">
  <div class="row">
    <div class="col-lg-">
    </div>
　<%= form_with model: @item, url: admin_item_path(@item), local: true do |f|%>
  <h4>商品画像 </h4>
  <%= f.attachment_field :image, autofocus: true %>

  <h4>商品名</h4>
  <%= f.text_field :name, autofocus: true %>

  <h4>商品説明</h4>
  <%= f.text_area :introduction, autofocus: true %>

  <h4>ジャンル</h4>
    <%= f.label :genre, 'ジャンル' %>
    <%=f.collection_select(:genre_id, Genre.all, :id, :name)%>

  <h4>税抜価格</h4>
  <%= f.text_field :price, autofocus: true %>

  <h4>販売ステータス</h4>
  <%= f.radio_button :is_active, :true %>
  <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
  <%= f.radio_button :is_active, :false %>
  <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
  <h4></h4>
  <%= f.submit "変更を保存" ,class: "btn btn-success"%>
<% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<%= link_to "新規登録", new_admin_item_path, class: "btn btn-success" %>

<h4>商品一覧</h4>
<div class="container">
  <div class="row">
    <table class="table table-striped">
      <thead>
        <tr>
          <td><strong>商品ID</strong></td>
          <td><strong>商品名</strong></td>
          <td><strong>税抜価格</strong></td>
          <td><strong>ジャンル</strong></td>
          <td><strong>ステータス</strong></td>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%=item.id  %></td>
            <td><%=link_to item.name,admin_item_path(item.id),class: "text-dark" %></td>
            <td><%= item.price %></td>
            <td><%= item.genre_id %></td>
          <% if item.is_active==true %>
            <td class="text-success"> 販売中</td>
　　　  　<% else  %>
　　　    　<td class="text-success">販売停止中</td>
          <% end %>
         </tr>
       <% end %>
     </tbody>
  </table>
 <%= paginate @items %>
 </div>
</div>

app/views/admin/items/new.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <% @item.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<h4>商品新規登録</h4>
<div class="container">
  <div class="row">
    <div class="col-lg-4">
    </div>
     <%= form_with model: @item, url: admin_items_path, local: true do |f|%>
        <h4>商品画像 </h4>
        <%= f.attachment_field :image, autofocus: true%>

        <h4>商品名</h4>
        <%= f.text_field :name, :placeholder => "商品名" ,autofocus: true %>

        <h4>商品説明</h4>
        <%= f.text_area :introduction, :placeholder => "ここに説明を記述します" ,autofocus: true %>

        <h4>ジャンル</h4>
        <%= f.label :genre_id, 'ジャンル' %>
        <%= f.select :genre_id, {'ケーキ': 1, '和菓子': 2, 'プリン': 3, 'キャンディ': 4}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>

        <h4>税抜価格</h4>
        <%= f.text_field :price, :placeholder => "1000" ,autofocus: true %><p>円</p>
        <h4>販売ステータス</h4>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active, "販売中", {value: :true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
        <h4></h4>
        <%= f.submit "新規登録",class: "btn btn-success" %>
      <% end %>

  </div>
</div>

app/views/admin/items/show.html.erb
<h4 >商品詳細</h4>
<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <%= attachment_image_tag @item, :image, size: "300x300", format: 'jpeg' %>
    </div>
 <table>
   <tbody>
     <tr>
       <td>商品名</td>
       <td> <%=@item.name %></td>
     </tr>
     <tr>
       <td>商品説明</td>
       <td><%=@item.introduction %></td>
     </tr>
     <tr>
       <td>ジャンル</td>
       <td><%=@item.genre.name %></td>
     </tr>
     <tr>
       <td>税込価格（税抜価格）</td>
       <td><%=(@item.price*1.1).round(0)%>(<%=@item.price %>)円</td>
     </tr>
     <tr>
       <td>販売ステータス</td>
       <% if @item.is_active==true %>
       <td class="text-success">販売中</td>
　     <% else  %>
　     <td class="text-success">販売停止中</td>
       <% end %>
     </tr>
     <tr>
       <td><%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success"%></td>
     </tr>
   </tbody>
 </table>
 </div>
</div>

app/views/admin/orders/show.html.erb
<h4>注文履歴詳細</h4>
<%= form_with model: @order, url: admin_order_path, local: true do |f| %>
<table>
  <tbody>
   <tr>
     <td><strong>購入者</strong></td>
     <td>
     <%= link_to admin_customer_path(@order.customer) do %>
     <%=@order.customer.fullname%>
     <% end %>
     </td>
   </tr>
   <tr>
     <td><strong>注文日</strong></td>
     <td><%=@order.created_at%></td>
   </tr>
   <tr>
     <td><strong>配送先</strong></td>
     <td><%=@order.address%></td>
   </tr>
   <tr>
     <td><strong>支払方法</strong></td>
     <td><%=@order.payment_method%></td>
   </tr>
   <tr>
     <td><strong>注文ステータス</strong></td>
     <td><%#= f.select :status, {'入金待ち': 0, '入金確認': 1, '制作中': 2, '発送準備中': 3,'発送済み': 4}%></td>
   <td><%=f.select :status, Order.statuses.keys, {prompt: "選択してください"}%></td>
     <td><%=f.submit "更新",class: "btn btn-success" %></td>
   </tr>
  </tbody>
</table>
<% end %>

<table>
  <thead>
    <tr>
       <td><strong>商品名</strong></td>
       <td><strong>単価（税込）</strong></td>
       <td><strong>数量</strong></td>
       <td><strong>小計</strong></td>
       <td><strong>制作ステータス</strong></td>
    </tr>
  </thead>
  <tbody>
    <%  @order_details.each do |order_detail|%>
    <tr>
      <td><%=order_detail.order.name%></td>
      <td><%=order_detail.price%></td>
      <td><%=order_detail.amount%></td>
      <td><%=(order_detail.price)*(order_detail.amount)%></td>
      <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), local: true do |f|%>
        <td><%=f.select :making_status,OrderDetail.making_statuses.keys,{prompt: "選択してください"}%></td>

        <td><%=f.submit "更新", class: "btn btn-success"%></td>
      <% end %>

      <td><%= order_detail.order.total_payment%></td>
      <td><%= order_detail.order.shipping_cost%></td>
      <td><%=(order_detail.order.total_payment).to_i+(order_detail.order.shipping_cost).to_i%></td>
    </tr>
    <% end %>
  </tbody>

</table>