config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    get 'customers/edit' => 'customers#edit'
    get 'customers' => 'customers#show'
  end
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'public/homes#top'
   namespace :admin do
       resources :customers, only: [:index, :show, :edit, :update]
       get 'admin' => 'homes#top'
       resources :items, except: [:destroy]
       resources :genres, only: [:index, :create, :edit, :update]
       resources :orders, only: [:show,:update]
       resources :order_details, only: [:update]
   end
   scope module: :public do
     delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
     resources :cart_items, only: [:index, :create, :update, :destroy]
     get 'about' => 'homes#about'
     resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :show, :update]
     get 'customers/withdraw' => 'customers#withdraw'
     patch 'customers/withdraw_update' => 'customers#withdsraw_update'
     get 'orders/thanks' => 'orders#thanks'
     post 'orders/verification' => 'orders#verification'
     resources :orders, only: [:new, :show, :index, :create]
     resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def view_dear_address
    self.postal_code + self.address + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cart_items
         has_many :addresses
         has_many :orders

         def fullname
          last_name+first_name
         end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    validates :image, presence: true
    validates :name, presence: true
    validates :introduction, presence: true
    validates :genre_id, presence: true
    validates :price, presence: true
    validates :is_active, presence: true

    belongs_to :genre
    has_many :cart_items
    has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4
  }

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3
  }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    end
  end

    private
    def customer_params
      params.require(:customer).permit(:id,:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,:is_deleted)
    end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to edit_admin_genre_path(@genre.id)
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    end
  end
private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    end
  end

 private
    def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :price, :is_active)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @customer = @order.customer
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id)
    end
  end

  private
   def order_params
      params.require(:order).permit(:status)
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_admin_path
    else
      root_path
    end
 end


  protected


  def configure_permitted_parameters
    if resource_name==:customer
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<%= @customer.fullname%>さんの会員情報編集
<div class="container">
  <div class="row">
    <div class="col-lg-6">
<%= form_with model: @customer,url: admin_customer_path(@customer.id), local:true do |f|%>
 <table >
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= f.text_field :id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%=f.text_field :last_name%><%=f.text_field :first_name%></td>
    </tr>
    <tr>
       <tr>
      <td>フリガナ</td>
      <td><%=f.text_field :last_name_kana%><%=f.text_field :first_name_kana%></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%=f.text_field :address%></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%=f.text_field :telephone_number%></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= f.text_field :email%></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td>
       <%= f.radio_button :is_deleted, :false %>
       <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
       <%= f.radio_button :is_deleted, :true %>
       <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
      </td>
    </tr>
    <tr>
      <td>
         <%= f.submit "変更を保存", class: "btn btn-success"%>
      </td>
    </tr>
  </tbody>
 </table>
 <% end %>
</div>
<div class="col-lg-6">
</div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>
<div class="container">
  <div class="row">
    <div class="col-lg-4"></div>

<table  class="table">
  <thead class="thead-light">
    <tr>
    <td><strong>会員ID</strong></td>
    <td ><strong>氏名</strong></td>
    <td><strong>メールアドレス</strong></td>
    <td><strong>ステータス</strong></td>
    </tr>
  </thead>

  <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%=customer.id%></td>
          <td >
          <%= link_to admin_customer_path(customer.id),class: "text-dark" do %>
          <%= customer.fullname%>
          <% end %>
          </td>
          <td><%=customer.email%></td>
          <% if customer.is_deleted!=true %>
          <td class="text-success">有効</td>
          <%else%>
          <td class="text-success">退会</td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
</table>
 <%= paginate @customers %>
   <div class="col-lg-4"></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<%= @customer.fullname %>さんの会員詳細
<div class="container">
  <div class="row">
    <div class="col-lg-6">
<table class="table table-borderless">
  <tbody>
    <tr>
      <td><strong>会員ID</strong></td>
      <td><strong><%= @customer.id %></strong></td>
    </tr>
    <tr>
      <td><strong>氏名</strong></td>
      <td><strong><%= @customer.last_name %><%= @customer.first_name %></strong></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td><strong>郵便番号</strong></td>
      <td><strong><%= @customer.postal_code %></strong></td>
    </tr>
    <tr>
      <td><strong>住所</strong></td>
      <td><strong><%= @customer.address %></strong></td>
    </tr>
    <tr>
      <td><strong>電話番号</strong></td>
      <td><strong><%= @customer.telephone_number %></strong></td>
    </tr>
    <tr>
      <td><strong>メールアドレス</strong></td>
      <td><strong><%= @customer.email %></strong></td>
    </tr>
    <tr>
      <td><strong>会員ステータス</strong></td>
      <% if @customer.is_deleted!=true %>
      <td class="text-success">有効</td>
      <%else%>
      <td class="text-success">退会</td>
      <% end %>
    </tr>
  </tbody>
</table>

<%= link_to "編集する", edit_admin_customer_path(@customer),class: "btn btn-success" %>
<%= link_to "注文履歴一覧を見る", admin_admin_path, class: "btn btn-primary"%>
</div>
<div class="col-lg-6">
</div>
 </div>
</div>