config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    get 'customers/edit' => 'customers#edit'
    get 'customers' => 'customers#show'
  end
  devise_for :customers, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: 'public/homes#top'
   namespace :admin do
       resources :customers, only: [:index, :show, :edit, :update]
       get 'admin' => 'homes#top'
       resources :items, except: [:destroy]
       resources :genres, only: [:index, :create, :edit, :update]
       resources :orders, only: [:show,:update]
       resources :order_details, only: [:update]
   end
   scope module: :public do
     delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
     resources :cart_items, only: [:index, :create, :update, :destroy]
     get 'about' => 'homes#about'
     resources :items, only: [:index, :show]
    resources :customers, only: [:edit, :show, :update]
     get 'customers/withdraw' => 'customers#withdraw'
     patch 'customers/withdraw_update' => 'customers#withdsraw_update'
     get 'orders/thanks' => 'orders#thanks'
     post 'orders/verification' => 'orders#verification'
     resources :orders, only: [:new, :show, :index, :create]
     resources :addresses, only: [:index, :edit, :create, :update, :destroy]
   end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def view_dear_address
    self.postal_code + self.address + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :cart_items
         has_many :addresses
         has_many :orders

         def fullname
          last_name+first_name
         end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    attachment :image
    validates :image, presence: true
    validates :name, presence: true
    validates :introduction, presence: true
    validates :genre_id, presence: true
    validates :price, presence: true
    validates :is_active, presence: true

    belongs_to :genre
    has_many :cart_items
    has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer
  enum status: {
    入金待ち:0,入金確認:1,製作中:2,発送準備中:3,発送済み:4
  }

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: {
    製作不可:0,製作待ち:1,製作中:2,製作完了:3
  }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
   @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    end
  end

 private
    def item_params
    params.require(:item).permit(:name, :introduction, :image, :genre_id, :price, :is_active)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
 def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_admin_path
    else
      root_path
    end
 end


  protected


  def configure_permitted_parameters
    if resource_name==:customer
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number])
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class ="container">
        <a class="navbar-brand" href="#!">LOGO</a>

        <% if customer_signed_in? %>
        <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to "マイページ", customers_path, class:"btn btn-outline-dark" %>
        </li>
        <li>
          <%= link_to "商品一覧", items_path, class:"btn btn-outline-dark" %>
        </li>
        <li>
          <%= link_to "カート", cart_items_path, class:"btn btn-outline-dark" %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class:"btn btn-outline-dark" %>
        </li>
      </ul>
       <% elsif admin_signed_in? %>
      <ul class="navbar-nav ml-auto">
        <li>
          <%= link_to "商品一覧", admin_items_path,class:"btn btn-outline-dark" %>
        </li>
        <li>
          <%= link_to "会員一覧", admin_customers_path,class:"btn btn-outline-dark" %>
        </li>
        <li>
          <%= link_to "注文履歴一覧", admin_admin_path,class:"btn btn-outline-dark" %>
        </li>
        <li>
          <%= link_to "ジャンル一覧", admin_genres_path,class:"btn btn-outline-dark" %>
        </li>
         <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class:"btn btn-outline-dark" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav ml-auto">
         <li>
           <%= link_to "About", about_path,class:"btn btn-outline-dark" %>
         </li>
         <li>
           <%= link_to "商品一覧", items_path,class:"btn btn-outline-dark" %>
         </li>
         <li>
           <%= link_to "新規登録", new_customer_registration_path,class:"btn btn-outline-dark" %>
         </li>
         <li>
           <%= link_to "ログイン", new_customer_session_path,class:"btn btn-outline-dark" %>
         </li>
       </ul>
    <% end %>
    </div>
    </nav>
    </header>

     <%= yield %>

  <footer>
  </footer>
  </body>
</html>